//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_JSTC_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocument
    {
        public int Document_Id { get; set; }
        public string Document_Folder_Path { get; set; }
        public int Product_Id { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
    }
}
