//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_JSTC_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManufacturer
    {
        public int Manuf_Id { get; set; }
        public string Manuf_Name { get; set; }
        public string Manuf_Web { get; set; }
        public int User_Id { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
