//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_JSTC_DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblDocuments = new HashSet<tblDocument>();
            this.tblPropertyValues = new HashSet<tblPropertyValue>();
        }
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public string Product_Image { get; set; }

        [Display(Name = "Series: ")]
        public string Product_Series { get; set; }

        [Display(Name = "Mode: ")]
        public string Product_Model { get; set; }

        [Display(Name = "Model Year: ")]
        public System.DateTime Product_Model_Year { get; set; }

        [Display(Name = "Info: ")]
        public string Product_Series_Info { get; set; }
        public Nullable<bool> Product_Featured { get; set; }

        public string SubCategory { get; set; }

        [Display(Name = "Manufacturer: ")]
        public string Manufacturer { get; set; }
        public string Category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocument> tblDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPropertyValue> tblPropertyValues { get; set; }
    }
}
